// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eufcorzymrfmghvuzppr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1ZmNvcnp5bXJmbWdodnV6cHByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2Mjc1MjYsImV4cCI6MjA2OTIwMzUyNn0.FlSGJdfRz7o-bv42u4smvGGZ19RM0Fnbr3kUwEqA9OI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});